### ISSUE TITLE
Fetching Payment details by Java ApiResponse got error

### ISSUE THREAD

**Issue by naved997** [cashfree/cashfree-pg-sdk-java#39]
ApiResponse<OrderEntity> response = cashfree.PGOrderFetchPayments(xApiVersion, "RB79-126054895", null, null, null);

This Api call is give an error of incompatible type please check this issue.
![ErrorCashfree](https://github.com/cashfree/cashfree-pg-sdk-java/assets/42957042/d8d8fc15-6c1c-4623-b4e8-c3a5c852aa8c)

**Comment by rajnandan1** [comment]
@suhas-cashfree can you check this?

**Comment by suhas-cashfree** [comment]
What is the version you are using @naved997 ?

**Comment by naved997** [comment]
I am using com.cashfree.pg.java version-4.0.2 @suhas-cashfree

**Comment by suhas-cashfree** [comment]
Hi @naved997 
Are you trying it like this ?

`ApiResponse<List<PaymentEntity>> response = cashfree.PGOrderFetchPayments("2023-08-01", "RB79-126054895",null, null, null);`

**Comment by naved997** [comment]
Hi @suhas-cashfree 
I tried this and it works but then details did not fetched by response.getData() it gives error

**Comment by suhas-cashfree** [comment]
Okay Okay

**Comment by naved997** [comment]
Ok i am waiting and thank you for considering this error

**Comment by naved997** [comment]
@suhas-cashfree issue is persist in new version also

**Comment by suhas-cashfree** [comment]
What is the error you are getting ?

**Comment by suhas-cashfree** [comment]
`package org.example;
import com.cashfree.ApiResponse;
import com.cashfree.model.OrderEntity;
import com.cashfree.*;
import com.cashfree.model.PaymentEntity;

import java.util.List;

public class Main {
    public static void main(String[] args) {
        Cashfree.XClientId = "<clientId>";
        Cashfree.XClientSecret = "<clientSecret>";
        Cashfree.XEnvironment = Cashfree.SANDBOX;

        Cashfree cashfree = new Cashfree();

        try {
            ApiResponse<List<PaymentEntity>> response = cashfree.PGOrderFetchPayments("2023-08-01", "<order_id>",null, null, null);
            System.out.println(response.getData());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}`

**Comment by naved997** [comment]
Yes i tried the above code and it worked but how to get payment details by response because it only work for response.getData() not for other like response.getData().getPaymentStatus();

**Comment by suhas-cashfree** [comment]
GetData returns a list. Loop through and then get the status

**Comment by naved997** [comment]
@suhas-cashfree How can i do this? I request you to help in this regard please

**Comment by suhas-cashfree** [comment]
Hi @naved997 
`try {
            ApiResponse<List<PaymentEntity>> response = cashfree.PGOrderFetchPayments("2023-08-01", "order_342bAHtHiGpa2XePHbvRdu22S7p8U",null, null, null);
            List<PaymentEntity> paymentEntities = response.getData();
            for (int i = 0; i < paymentEntities.size(); i++) {
                System.out.println(paymentEntities.get(i).getPaymentStatus());
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }`

**Comment by naved997** [comment]
@suhas-cashfree this is also not working getPaymentStatus() gives error

**Comment by suhas-cashfree** [comment]
Can you check the version again and try.
I tested it before pasting the code here.

If it still persists, write to care@cashfree.com
May be a call can be setup to help you further

**Comment by naved997** [comment]
@suhas-cashfree your code in github is shown like this:
`try {
ApiResponse<List> response = cashfree.PGOrderFetchPayments("2023-08-01", "order_342bAHtHiGpa2XePHbvRdu22S7p8U",null, null, null);

// Looping and reading status
List paymentEntities = response.getData();
for (int i = 0; i < paymentEntities.size(); i++) {
System.out.println(paymentEntities.get(i).getPaymentStatus());
}
} catch (Exception e) {
System.out.println(e.getMessage());
}`

I changed to:
`ApiResponse<List<PaymentEntity>> response1 = cashfree.PGOrderFetchPayments("2023-08-01", "order_342bAHtHiGpa2XePHbvRdu22S7p8U",null, null, null);
           List <PaymentEntity> paymentEntities = response1.getData();

           for (int i = 0; i < paymentEntities.size(); i++) {
               System.out.println(paymentEntities.get(i).getPaymentStatus());
           }`

It works now.

**Comment by suhas-cashfree** [comment]
Closing this issue. Please open a new one if the issue still persists
