### ISSUE TITLE
SDK not updated with api response

### ISSUE THREAD

**Issue by saurabhpal97** [cashfree/cashfree-pg-sdk-java#8]
The create order api is now returning an attribute called customer_uid, which is failing during deserialization in the java sdk as customer_uid is not a part of the CFCustomerDetails object.

{
--
2 | "cf_order_id": 2151987171,
3 | "created_at": "2023-10-13T22:46:10+05:30",
4 | "customer_details": {
5 | "customer_id": "409128494",
6 | "customer_name": null,
7 | "customer_email": null,
8 | "customer_phone": "9876543210",
9 | "customer_uid": null
10 | },
11 | "entity": "order",
12 | "order_amount": 636,
13 | "order_currency": "INR",
14 | "order_expiry_time": "2023-11-12T22:46:10+05:30",
15 | "order_id": "order_4105752WiZTisMERUFTJGDkoO8pEl3tuq",
16 | "order_meta": {
17 | "return_url": null,
18 | "notify_url": null,
19 | "payment_methods": null
20 | },
21 | "order_note": null,
22 | "order_splits": [],
23 | "order_status": "ACTIVE",
24 | "order_tags": null,
25 | "payment_session_id": "session_5awMLI1sM8qmbztBA-bKtBtrHttTzrkEifRFOiT3e8ZMcytARS7a5oj-5VfFbnt-nrauHwrX2x3YXtvR7tVvZgf0ngH8eNGLlFSSnJAXzi3_",
26 | "payments": {
27 | "url": "https://sandbox.cashfree.com/pg/orders/order_4105752WiZTisMERUFTJGDkoO8pEl3tuq/payments"
28 | },
29 | "refunds": {
30 | "url": "https://sandbox.cashfree.com/pg/orders/order_4105752WiZTisMERUFTJGDkoO8pEl3tuq/refunds"
31 | },
32 | "settlements": {
33 | "url": "https://sandbox.cashfree.com/pg/orders/order_4105752WiZTisMERUFTJGDkoO8pEl3tuq/settlements"
34 | },
35 | "terminal_data": null
36 | }

**Comment by prasunparijat-cashfree** [comment]
Hello @saurabhpal97.  Please take the latest version pull 2.1.7, SDK response is updated now.
